'type: documentation':
  - '**/*.md'
  - 'docs/**/*'

'type: tests':
  - 'tests/**/*'
  - '**/*.test.*'
  - '**/*.spec.*'

'type: build':
  - 'package.json'
  - 'package-lock.json'
  - '*config.*'

'type: ci':
  - '.github/workflows/**/*'

'size: small':
  - any: ['**/*']
    count: 1..10

'size: large':
  - any: ['**/*']
    count: 21..100
